import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { gunzipSync } from 'node:zlib'
import {
  AREA_PARAMS,
  eaqiBandForValue,
  EAQI_POLLUTANTS,
  MAX_AGE_SEC,
  regionBandAllowed,
  type AreaParam,
  type AreaSnapshot,
  type AreaStats,
  type EaqiBand,
  type EaqiPollutant,
  type StationCollection,
  type StationFeature,
} from '@aerismap/shared'

/**
 * Hourly NUTS area aggregation (AREA MODE).
 *
 * Stations are assigned to NUTS-3 polygons from the vendored 1:3M assignment
 * set (ingest/data/nuts3-assign.geojson.gz, regenerated by
 * scripts/prepare-boundaries.ts); a NUTS-3 region's NUTS-2 parent is its
 * 5-char id truncated to 4 chars (NUTS codes are hierarchical — this holds
 * for the NUTS-2021 UK splice too). NUTS-2 aggregates run over that region's
 * stations directly (a single median, NOT a median of NUTS-3 medians).
 *
 * Point-in-polygon is a hand-rolled even-odd ray cast with a per-feature
 * bbox prefilter — measured ~100 ms for 14k stations × 1.3k polygons, so no
 * geometry library is needed or wanted here.
 */

/** Vendored 1:3M NUTS-3 assignment boundaries (see scripts/prepare-boundaries.ts). */
export const ASSIGN_BOUNDARIES_PATH = fileURLToPath(
  new URL('../data/nuts3-assign.geojson.gz', import.meta.url)
)

/**
 * Coastal/generalization fallback: a point missing every polygon is assigned
 * to the candidate (bbox expanded by 0.03°) whose nearest polygon vertex is
 * within ~2 km. Beyond that it stays unassigned — RU/BY/AM/MD/GE and
 * country-only UA stations have no NUTS polygons by design.
 */
const FALLBACK_BBOX_EXPAND_DEG = 0.03
const FALLBACK_MAX_VERTEX_KM = 2
const KM_PER_DEG_LAT = 110.574
const KM_PER_DEG_LON_EQUATOR = 111.32

type Ring = ReadonlyArray<readonly number[]>

interface NutsAssignFeature {
  type: 'Feature'
  properties: { NUTS_ID: string }
  geometry:
    | { type: 'Polygon'; coordinates: Ring[] }
    | { type: 'MultiPolygon'; coordinates: Ring[][] }
}

interface NutsAssignCollection {
  type: 'FeatureCollection'
  features: NutsAssignFeature[]
}

interface PreparedRegion {
  id: string
  /** [minLon, minLat, maxLon, maxLat] over every ring. */
  bbox: [number, number, number, number]
  /** All rings (outer + holes, across MultiPolygon parts) — even-odd handles holes. */
  rings: Ring[]
}

export interface BoundaryIndex {
  regions: PreparedRegion[]
  /**
   * Distinct NUTS-3 ids + their distinct NUTS-2 prefixes = meta.counts
   * .areasTotal. Note this is 1,861 for the vendored set while the published
   * boundary GeoJSONs hold 1,864 features: Bosnia's BA01–BA03 exist at
   * NUTS-2 but have no NUTS-3 subdivision in GISCO 2024, so no station can
   * ever roll up into them — they are not part of the aggregation universe
   * and render as no-data.
   */
  totalRegions: number
  nuts3Count: number
  nuts2Count: number
}

/** Build the assignment index (bboxes + flattened rings) from a parsed collection. */
export function prepareBoundaryIndex(collection: NutsAssignCollection): BoundaryIndex {
  if (collection?.type !== 'FeatureCollection' || !Array.isArray(collection.features)) {
    throw new Error('assignment boundaries: not a FeatureCollection')
  }
  const regions: PreparedRegion[] = []
  const nuts2 = new Set<string>()
  for (const feature of collection.features) {
    const id = feature.properties?.NUTS_ID
    if (typeof id !== 'string' || id.length < 4) {
      throw new Error(`assignment boundaries: feature with missing/short NUTS_ID ${JSON.stringify(id)}`)
    }
    const rings: Ring[] =
      feature.geometry.type === 'Polygon'
        ? feature.geometry.coordinates
        : feature.geometry.coordinates.flat()
    let minLon = Infinity
    let minLat = Infinity
    let maxLon = -Infinity
    let maxLat = -Infinity
    for (const ring of rings) {
      for (const position of ring) {
        const lon = position[0]!
        const lat = position[1]!
        if (lon < minLon) minLon = lon
        if (lon > maxLon) maxLon = lon
        if (lat < minLat) minLat = lat
        if (lat > maxLat) maxLat = lat
      }
    }
    regions.push({ id, bbox: [minLon, minLat, maxLon, maxLat], rings })
    nuts2.add(id.slice(0, 4))
  }
  // Countries without a NUTS-3 subdivision (Bosnia) are spliced into the
  // assignment set with their NUTS-2 polygons, so an assignment id can BE a
  // NUTS-2 id — count each distinct region once, not per level.
  const assignmentIds = new Set(regions.map((r) => r.id))
  const nuts2Only = [...nuts2].filter((id) => !assignmentIds.has(id))
  return {
    regions,
    nuts3Count: regions.length,
    nuts2Count: nuts2.size,
    totalRegions: regions.length + nuts2Only.length,
  }
}

/** Load + gunzip + index the vendored assignment boundaries (once per run). */
export async function loadBoundaryIndex(path: string = ASSIGN_BOUNDARIES_PATH): Promise<BoundaryIndex> {
  const body = await readFile(path)
  const parsed = JSON.parse(gunzipSync(body).toString('utf8')) as NutsAssignCollection
  return prepareBoundaryIndex(parsed)
}

/** Even-odd ray cast over every ring — holes and MultiPolygon parts included. */
function ringsContain(rings: readonly Ring[], lon: number, lat: number): boolean {
  let inside = false
  for (const ring of rings) {
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
      const xi = ring[i]![0]!
      const yi = ring[i]![1]!
      const xj = ring[j]![0]!
      const yj = ring[j]![1]!
      if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) {
        inside = !inside
      }
    }
  }
  return inside
}

/** Equirectangular approximation — plenty at the ~2 km fallback scale. */
function distanceKm(lon1: number, lat1: number, lon2: number, lat2: number): number {
  const kmPerDegLon = KM_PER_DEG_LON_EQUATOR * Math.cos(((lat1 + lat2) / 2) * (Math.PI / 180))
  const dx = (lon2 - lon1) * kmPerDegLon
  const dy = (lat2 - lat1) * KM_PER_DEG_LAT
  return Math.sqrt(dx * dx + dy * dy)
}

function nearestVertexKm(region: PreparedRegion, lon: number, lat: number): number {
  let best = Infinity
  for (const ring of region.rings) {
    for (const position of ring) {
      const d = distanceKm(lon, lat, position[0]!, position[1]!)
      if (d < best) best = d
    }
  }
  return best
}

/**
 * NUTS-3 id for a point, or undefined when it lies outside every polygon and
 * the coastal fallback (expanded-bbox candidates, nearest vertex ≤ ~2 km)
 * finds nothing either.
 */
export function assignRegion(index: BoundaryIndex, lon: number, lat: number): string | undefined {
  for (const region of index.regions) {
    const [minLon, minLat, maxLon, maxLat] = region.bbox
    if (lon < minLon || lon > maxLon || lat < minLat || lat > maxLat) continue
    if (ringsContain(region.rings, lon, lat)) return region.id
  }
  let bestId: string | undefined
  let bestKm = FALLBACK_MAX_VERTEX_KM
  for (const region of index.regions) {
    const [minLon, minLat, maxLon, maxLat] = region.bbox
    if (
      lon < minLon - FALLBACK_BBOX_EXPAND_DEG ||
      lon > maxLon + FALLBACK_BBOX_EXPAND_DEG ||
      lat < minLat - FALLBACK_BBOX_EXPAND_DEG ||
      lat > maxLat + FALLBACK_BBOX_EXPAND_DEG
    ) {
      continue
    }
    const km = nearestVertexKm(region, lon, lat)
    if (km <= bestKm) {
      bestKm = km
      bestId = region.id
    }
  }
  return bestId
}

/** Median of a non-empty list, rounded to 1 decimal (the published precision). */
export function median1(values: readonly number[]): number {
  const sorted = [...values].sort((a, b) => a - b)
  const mid = sorted.length >> 1
  const median = sorted.length % 2 === 1 ? sorted[mid]! : (sorted[mid - 1]! + sorted[mid]!) / 2
  return Math.round(median * 10) / 10
}

export interface BuiltAreas {
  snapshot: AreaSnapshot
  areasColored: number
  areasTotal: number
  /** Included (non-stale, non-model) stations that matched no NUTS-3 polygon. */
  unassignedStations: number
}

function buildStats(stations: readonly StationFeature[], now: Date): AreaStats {
  let nRef = 0
  let nCom = 0
  const med: Partial<Record<AreaParam, number>> = {}
  const cnt: Partial<Record<AreaParam, number>> = {}
  /** Raw included values per param, kept for the two-station min rule. */
  const valuesByParam: Partial<Record<AreaParam, number[]>> = {}
  let hasParams = false

  for (const param of AREA_PARAMS) {
    const values: number[] = []
    for (const station of stations) {
      const { properties } = station
      // PM optics over-read in near-saturated air — drop this station's PM
      // medians contribution; its other params still count (plan §5.1).
      if (properties.pmHumidityBias && (param === 'pm2_5' || param === 'pm10')) continue
      // Spatial-QC-flagged readings (railed/stuck sensors, see qc.ts) are
      // excluded too — the two exclusions compose, either suffices.
      if (properties.qc?.includes(param)) continue
      const reading = properties.values[param]
      if (!reading) continue
      // Same freshness rule the snapshot EAQI uses: readings past the
      // per-kind horizon stay visible in popups but must not drive aggregates.
      const ageSec = (now.getTime() - Date.parse(reading.ts)) / 1000
      if (!(ageSec <= MAX_AGE_SEC[properties.kind])) continue
      values.push(reading.v)
    }
    if (values.length > 0) {
      med[param] = median1(values)
      cnt[param] = values.length
      valuesByParam[param] = values
      hasParams = true
    }
  }

  for (const station of stations) {
    if (station.properties.kind === 'reference') nRef++
    else if (station.properties.kind === 'community') nCom++
  }

  const stats: AreaStats = { n: stations.length, nRef, nCom }
  if (hasParams) {
    stats.med = med
    stats.cnt = cnt
  }

  // Region band (graduated gating, decided 2026-07-21 — the old ≥3-station
  // cliff is gone): each EAQI pollutant is banded and the worst ALLOWED band
  // wins. Per-pollutant banding value: with exactly two contributing stations
  // the MIN of the two (AREA_TWO_STATION_RULE — one liar can't paint a
  // region; the published med stays the median), otherwise the published
  // median. regionBandAllowed then gates by count: cnt ≥ 2 always allowed,
  // cnt == 1 only for bands ≤ 3 — one sensor may say "fine", never
  // "emergency". Ties keep the first pollutant in EAQI_POLLUTANTS order
  // (strict >, mirroring shared computeEaqi).
  let worst: { band: EaqiBand; pollutant: EaqiPollutant } | undefined
  for (const pollutant of EAQI_POLLUTANTS) {
    const values = valuesByParam[pollutant]
    if (!values) continue
    const bandValue = values.length === 2 ? Math.min(values[0]!, values[1]!) : med[pollutant]!
    const band = eaqiBandForValue(pollutant, bandValue)
    if (band === undefined || !regionBandAllowed(band, values.length)) continue
    if (worst === undefined || band > worst.band) worst = { band, pollutant }
  }
  if (worst) {
    stats.eaqi = worst.band
    stats.pollutant = worst.pollutant
  }
  return stats
}

/**
 * Aggregate the station snapshot into the AreaSnapshot published as
 * latest/areas.json.gz — one flat map keyed by NUTS_ID over BOTH levels
 * (4-char = NUTS-2, 5-char = NUTS-3), only for regions with ≥1 included
 * station. Deterministic: keys sorted, independent of input feature order.
 */
export function buildAreas(collection: StationCollection, index: BoundaryIndex, now: Date): BuiltAreas {
  const byRegion = new Map<string, StationFeature[]>()
  const hotspotAssignments: Array<[StationFeature, string]> = []
  let unassignedStations = 0

  for (const feature of collection.features) {
    const { properties } = feature
    if (properties.kind === 'model') continue
    // Only non-stale stations are included; coarsened-coordinate stations
    // (exactLocation false) stay in — the median is robust to small offsets.
    if (properties.stale) continue
    const [lon, lat] = feature.geometry.coordinates
    const nuts3 = assignRegion(index, lon, lat)
    if (!nuts3) {
      unassignedStations++
      continue
    }
    if (properties.hotspot) hotspotAssignments.push([feature, nuts3])
    // Set-dedupe: for spliced no-NUTS-3 countries (Bosnia) the assignment id
    // IS the NUTS-2 id — without the dedupe the station would count twice.
    for (const id of new Set([nuts3, nuts3.slice(0, 4)])) {
      const list = byRegion.get(id)
      if (list) list.push(feature)
      else byRegion.set(id, [feature])
    }
  }

  const areas: Record<string, AreaStats> = {}
  let areasColored = 0
  for (const id of [...byRegion.keys()].sort()) {
    const stats = buildStats(byRegion.get(id)!, now)
    areas[id] = stats
    if (stats.eaqi !== undefined) areasColored++
  }

  // Enrich hotspot stations with their regions' bands so the client can hide
  // rings that merely repeat the fill color under them (contrast rule).
  for (const [feature, nuts3] of hotspotAssignments) {
    const n3 = areas[nuts3]?.eaqi
    const n2 = areas[nuts3.slice(0, 4)]?.eaqi
    if (n2 !== undefined || n3 !== undefined) {
      feature.properties.regionBands = {
        ...(n2 !== undefined ? { n2 } : {}),
        ...(n3 !== undefined ? { n3 } : {}),
      }
    }
  }

  return {
    snapshot: { generatedAt: now.toISOString(), areas },
    areasColored,
    areasTotal: index.totalRegions,
    unassignedStations,
  }
}

/**
 * Carry-forward wrapper for the hourly run: any failure in loading the
 * boundaries or aggregating degrades to a ::warning and NO areas artifact
 * this run — the previously published latest/areas.json.gz stays in place
 * (the run never overwrites it with nothing), mirroring the stations
 * carry-forward philosophy in its simplest acceptable form.
 */
export async function buildAreasForRun(
  collection: StationCollection,
  now: Date,
  options: { path?: string; warn?: (message: string) => void } = {}
): Promise<BuiltAreas | undefined> {
  const warn = options.warn ?? ((m) => console.log(m))
  try {
    const index = await loadBoundaryIndex(options.path)
    return buildAreas(collection, index, now)
  } catch (err) {
    warn(
      `::warning::area aggregation failed: ${err instanceof Error ? err.message : String(err)}` +
        ' — skipping areas this run; the previous areas artifact stays in place'
    )
    return undefined
  }
}
